### ISSUE TITLE
Feature request: Tags for each fluid and its flowing variant

### ISSUE THREAD

**Issue by gigawhip** [RCXcrafter/Funky-Fluids#2]
Vanilla and many mods use individual tags per liquid to cluster just that liquid and its floating variant together, ex. `#minecraft:lava` encompasses only `minecraft:lava` and `minecraft:flowing_lava`. Some mods rely on these tags to be able to refer to both the source block and flowing block at the same time. Because this mod's fluids don't have these tags, mod and modpack authors would have to add new tags such as `#funkyfluids:oobleck` to get your fluids to interoperate as expected. It would be awesome if you could instead bake such tags into the mod directly.

**Comment by RCXcrafter** [comment]
added in version 1.1.1
